### ISSUE TITLE
On theme change opens keyboard pad

### ISSUE THREAD

**Issue by asavchuk** [arthurdenner/theme_mode_handler#3] opened 2020-05-20 10:05 UTC
On theme change opens keyboard pad. This happens only on first change theme invoke. The following changes do not open keyboard pad. The same expirience I noticed using dynamic_theme on which this package based. What is the reason for that?

**Comment by arthurdenner** [comment] 2020-05-20 10:28
Hi @asavchuk! 👋 

This is not intended behavior but I don't think it's caused by this package as well since we just switch a property on the `MaterialApp` widget, which triggers a rebuild of the widgets.

Is this something you can reproduce during development - in an emulator or a device - or in production as well? Could you provide a reproducible example so that I can investigate?

My wild guess would be that the rebuild causes the keyboard to open but that would be up something to be fixed on the consumer side (your app) since this library doesn't enforce that.

**Comment by asavchuk** [comment] 2020-05-20 10:45
> Is this something you can reproduce during development - in an emulator or a device - or in production as well?

I noticed it on emulator(android) and on a phone as well, both in development and production.

> Could you provide a reproducible example so that I can investigate?

I'll try to make a minimal example to show the expirience.

**Comment by asavchuk** [comment] 2020-05-20 14:54
you are right, that's something with the code, look at this. 
I commented LoginView(); although the logic does not invoke the LoginView() now  (because at the beginning `service.hasSignedUp == false` is true hence SignUpFormPage()  will be returned) and that behaviour with opened keyboard pad disapeared. how can it be?
About(); - is used just to complete else statement. 

Next time when I open the app `service.hasSignedUp` will be true so LoginView(); will be executed - but as I said earlier in this case there was no issue I described. 

```
...
home: Startup(),
        );
      },
    );
  }
}

class Startup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final service = locator<LocalStorageService>();

    if (service.hasSignedUp == false) {
      return SignUpFormPage();
    } else {
      return About();
      // return LoginView();
    }
  }
}
```

**Comment by arthurdenner** [comment] 2020-05-20 17:30
@asavchuk - hard to say, but check if there is some input on LoginView, maybe with autofocus.

I suppose you'd need to search for existing solutions or workarounds similar to your case on StackOverflow, maybe force the keyboard to be hidden on the same piece of code that updates the themeMode... it's a bit tricky for me to say.

I'm closing the issue since you've confirmed that it's not a problem on this package.

**Closed as completed by arthurdenner** 2020-05-20 17:30 UTC
Labels: question
